DROP DATABASE IF EXISTS SpotifyClone;

CREATE DATABASE SpotifyClone;

USE SpotifyClone;

CREATE TABLE Plans(
    `PLAN_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `PlAN_NAME` VARCHAR(20),
    `PlAN_VALUE` DECIMAL NOT NULL
) engine = InnoDB;

INSERT INTO Plans (PLAN_ID, PlAN_NAME, PlAN_VALUE)
VALUES
  ('1', 'gratuito','0'),
  ('2', 'universitário','5,99'),
  ('3', 'familiar','7,99');

CREATE TABLE UserDetail(
    `USER_ID` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(20) NOT NULL,
    `AGE` DECIMAL NOT NULL,
    `PLAN_ID` INT NOT NULL AUTO_INCREMENT,
    FOREIGN KEY (PLAN_ID) REFERENCES Plans(PLAN_ID)
) engine = InnoDB;

CREATE TABLE Artists(
    `ARTIST_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `ARTIST_NAME` VARCHAR(20)
) engine = InnoDB;

CREATE TABLE Albums(
    `ALBUM_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `ALBUM_NAME` VARCHAR(20),
    `ARTIST_ID` INT NOT NULL AUTO_INCREMENT,
    FOREIGN KEY (ARTIST_ID) REFERENCES Artists(ARTIST_ID)
) engine = InnoDB;

CREATE TABLE Songs (
    `SONG_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `SONG_NAME` VARCHAR(20),
    `ARTIST_ID` INT NOT NULL AUTO_INCREMENT,
    FOREIGN KEY (ARTIST_ID)
        REFERENCES Artists (ARTIST_ID)
)  ENGINE=INNODB;



INSERT INTO tabela2 (coluna1, coluna2)
VALUES
  ('exemplo de dados 1', 'exemplo de dados X'),
  ('exemplo de dados 2', 'exemplo de dados Y');