-- MySQL Script generated by MySQL Workbench
-- ter 28 set 2021 18:01:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpotifyClone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SpotifyClone` ;

-- -----------------------------------------------------
-- Schema SpotifyClone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpotifyClone` ;
USE `SpotifyClone` ;

-- -----------------------------------------------------
-- Table `SpotifyClone`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`album` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `id_artista` INT NOT NULL,
  PRIMARY KEY (`id_album`, `id_artista`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_album_artista1_idx` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `SpotifyClone`.`artista` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`artista` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`artista` (
  `id_artista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_artista`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`cancao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`cancao` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`cancao` (
  `id_cancao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `id_album` INT NOT NULL,
  PRIMARY KEY (`id_cancao`, `id_album`),
  INDEX `fk_cancao_album1_idx` (`id_album` ASC) VISIBLE,
  CONSTRAINT `fk_cancao_album1`
    FOREIGN KEY (`id_album`)
    REFERENCES `SpotifyClone`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`plano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`plano` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`plano` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`id_plano`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `valor_UNIQUE` (`valor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`usuario` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `id_plano` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_usuario_plano_idx` (`id_plano` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_plano`
    FOREIGN KEY (`id_plano`)
    REFERENCES `SpotifyClone`.`plano` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`usuario_ouviu_cancao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`usuario_ouviu_cancao` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`usuario_ouviu_cancao` (
  `id_usuario` INT NOT NULL,
  `id_cancao` INT NOT NULL,
  `id_album` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_cancao`, `id_album`),
  INDEX `fk_usuario_has_cancao_cancao1_idx` (`id_cancao` ASC, `id_album` ASC) VISIBLE,
  INDEX `fk_usuario_has_cancao_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_cancao_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SpotifyClone`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_cancao_cancao1`
    FOREIGN KEY (`id_cancao` , `id_album`)
    REFERENCES `SpotifyClone`.`cancao` (`id_cancao` , `id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`usuario_segue_artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotifyClone`.`usuario_segue_artista` ;

CREATE TABLE IF NOT EXISTS `SpotifyClone`.`usuario_segue_artista` (
  `id_usuario` INT NOT NULL,
  `id_artista` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_artista`),
  INDEX `fk_usuario_has_artista_artista1_idx` (`id_artista` ASC) VISIBLE,
  INDEX `fk_usuario_has_artista_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_artista_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SpotifyClone`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_artista_artista1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `SpotifyClone`.`artista` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
